name: MSG
main: MSG.Main.Core
version: 1.0
commands:
   start:
      description: Starts the game
      usage: /<command>
   end:
      description: Ends the game
      usage: /<command>
   setteam:
      description: Sets the player's team
      usage: /<command>